### ISSUE TITLE
 Error on a clean skeleton installation after "Which error handler do you want to use during development" step

### ISSUE THREAD

**Issue by dansol** [mezzio/mezzio-skeleton#109]
### Bug Report

 Error on a clean skeleton installation. 

![Mezzio-skeleton-error-handler-step](https://user-images.githubusercontent.com/3524858/208295784-00500a74-9cc0-41d2-abbe-c7c9b9b73743.png)

|    Q        |   A
|------------ | ------
| Version(s)  | x.y.z
| PHP           | 8.1
| Composer | 2.4.4
| OS             | Win10

#### Summary

Error after "Which error handler do you want to use during development?" question

#### Current behavior

Skeleton not installed. Composer shows an error.

#### How to reproduce

Run composer create-project mezzio/mezzio-skeleton mezzio ( see image) on a win10 device

#### Expected behavior

Skeleton installed.

**Comment by Ocramius** [comment]
Could you perhaps reproduce this again, but with `-vvv` during installation? 🤔

**Comment by froschdesign** [comment]
The error message is related to the following method:

https://github.com/mezzio/mezzio-skeleton/blob/8f8394a1a4440ab532bfce3fc065d0b01cc29f21/src/MezzioInstaller/OptionalPackages.php#L575-L586

---

But I cannot reproduce this problem. The installation works as expected.

**Comment by gsteel** [comment]
Looks like project root just needs  DIRECTORY_SEPARATOR rather than /

**Comment by dansol** [comment]
This is with -vvv option as per @Ocramius request

![Mezzio-skeleton-error-handler-step with vvv](https://user-images.githubusercontent.com/3524858/208312296-a9dcbd40-f279-45cd-b364-abb7f3c18463.png)

**Comment by froschdesign** [comment]
@gsteel 
You mean this can be wrong:

https://github.com/mezzio/mezzio-skeleton/blob/8f8394a1a4440ab532bfce3fc065d0b01cc29f21/src/MezzioInstaller/OptionalPackages.php#L189

**Comment by Nguimjeu** [comment]
Having the same issue with:
- php:8.2-fpm-alpine container
- composer 2.5.1

Seems like the `phpunit.xml.dist` file is not included into the installation when installing from the skeleton. Ignoring the error and running a `composer update` to "finish" the installation works; but that does not sounds OK. One could also create the file mentionnened above during the installation. But that also is not OK IMO.

**Comment by Xerkus** [comment]
phpunit.xml.dist is export ignored in .gitattributes by #97

**Comment by Ocramius** [comment]
Can anyone review https://github.com/mezzio/mezzio-skeleton/blob/8f8394a1a4440ab532bfce3fc065d0b01cc29f21/.gitattributes#L1-L8 and see which files should be dropped from that list, please? Sounds like that is the fix :D
