### ISSUE TITLE
No dependencies in newly created project

### ISSUE THREAD

**Issue by skoro** [mezzio/mezzio-skeleton#119]
### Bug Report

Installation of a new project with `composer create-project mezzio/mezzio-skeleton mezzio` ended up with the following messages and no dependencies are installed into `vendor` dir:
![image](https://user-images.githubusercontent.com/6389201/215260956-8c6caaff-6802-4cf9-8a37-5647ccfbdfbd.png)

|    Q        |   A
|------------ | ------
| Version(s)  | x.y.z
| PHP          | 8.2.1
| Composer | 2.5.1

#### Summary

No dependencies are installed.

#### Current behavior

No dependencies, `vendor` directory is missing.

#### How to reproduce

```sh
composer create-project mezzio/mezzio-skeleton mezzio
```

#### Expected behavior

Install dependecies

**Comment by samsonasik** [comment]
manually run `composer update` seems can be temporary solution, another way, probably composer.lock can be removed.

There was a PR from @boesing at : 

- https://github.com/mezzio/mezzio-skeleton/pull/56

**Comment by settermjd** [comment]
I've been getting that issue repeatedly for some time now. Pretty frustrating.
