### ISSUE TITLE
Mark supported options in the installer

### ISSUE THREAD

**Issue by weierophinney** [mezzio/mezzio-skeleton#29]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no

#### Summary

A new user tried to install using the combination of:

- Auryn for the container.
- AuraRouter for the router.
- Plates for templating.

On attempting to fire up the web server, the web page indicated:

```text
Expected 'Mezzio\Router\AuraRouter` to be invokable in ... mezzio-test/vendor/northwoods/container/src/ContainerException.php:22
```

northwoods/container is not directly maintained by Laminas, and, as such, I directed the user to (a) file an issue upstream, indicating the container did not pass the laminas/laminas-container-config-test test suite, and (b) choose an alternate container from the list of ones we directly support while testing (Pimple, Aura.Di, laminas-servicemanager).

They, quite correctly, noted that we should likely indicate the _supported_ options in the installer, to guide users towards those if they are unfamiliar with Mezzio.

**Comment by geerteltink** [comment]
@weierophinney  Something like this?

![image](https://user-images.githubusercontent.com/9497586/92565692-5b025480-f27b-11ea-9333-244946c07c2f.png)

**Comment by weierophinney** [comment]
Yes, exactly like that, @geerteltink ! Thanks!
