### ISSUE TITLE
Removal of `laminas/laminas-zendframework-bridge`

### ISSUE THREAD

**Issue by boesing** [mezzio/mezzio-skeleton#51]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| BC Break    | no

#### Summary

_Originally posted by @boesing in https://github.com/laminas/technical-steering-committee/issues/91#issuecomment-891899044_

As per the latest TSC meeting from [2021-08-02](https://github.com/laminas/technical-steering-committee/blob/8f72cf6af75f22436d752ce7e7c0f92c23336666/meetings/agenda.md#remove-laminaslaminas-zendframework-bridge-dependency-from-our-packages), the removal is experimental and we think we can drop it in minor versions as of now. Since the skeleton is special, we should only remove the bridge from this project without having any issues.

As per @michalbundyra, this should have been a part of this project anyways, so removal should be okay.

**Comment by lukaslangen** [comment]
Can be closed, as #60 removed it.
