### ISSUE TITLE
CI Pipeline does not test this component but the example component

### ISSUE THREAD

**Issue by boesing** [mezzio/mezzio-skeleton#54]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 3.8.0

#### Expected behavior

Since v3.8.0, we are using the new CI pipeline. This CI pipeline does not append `--no-scripts` to composer and thus, the CI pipeline executes the `OptionalPackages::install` logic, which applies default answers and thus ends up having a "setupped" project which has removed the `MezzioInstallerTest` logic.

**Therefore, this component is actually not tested since v3.8.0 at all**

**Comment by Xerkus** [comment]
It was resolved via #63
