### ISSUE TITLE
PHP 8.1 Support

### ISSUE THREAD

**Issue by lukaslangen** [mezzio/mezzio-skeleton#59]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 3.11.x

#### Summary

Although the project's composer.json states, that php 8.1 is supported, the installer fails because of dependencies, that are not yet updated to support php 8.1.

Most packages can be easily updated with `composer update` however some dependencies need some extra steps and thought.

The concerned dependencies are:
- `jsoumelidis/zend-sf-di-config`, which supports php 8.1 from  version 0.5
- `mezzio/mezzio-tooling`, which supports php 8.1 from version 2.1
- `mezzio/mezzio-aurarouter`

The `mezzio/mezzio-aurarouter` probably won't be able to support php 8.1 in the near future as the aura project seems to be abandoned. The aura projects don't seem to be actively maintained for quite some time now. Also their mailing list seems to be pretty dead (last mail on January 28th).

#### Current behavior

`composer create-project mezzio/mezzio-skeleton` fails, as composer cannot resolve an installable set of packages.
Afterwards `composer update` also fails, because of the aforementioned libraries.

#### How to reproduce

php version: 8.1
composer version: 2.1.5

Run `composer create-project mezzio/mezzio-skeleton`, after it fails run `composer update` inside the project.

#### Expected behavior

`composer create-project mezzio/mezzio-skeleton` runs successfully and creates the expected project.

#### Additional thoughts

I have already fixed the issues and will create PR in the next minutes, which I will link in the next comment.

While working on it, I also took #58 and #53, as for one I had to update `mezzio/mezzio-tooling` and second I had to fix a lot of tests, which where also failing for the auryn container. As there already exists the issue for it, I just removed it on the way.

**Comment by Ocramius** [comment]
@lukaslangen if we upgade `mezzio/mezzio-tooling` here, will it work, when not using `symfony/dependency-injectio` or the `aura/` router?

**Comment by lukaslangen** [comment]
The PR is in #60

**Comment by lukaslangen** [comment]
@Ocramius Can you elaborate a bit further? I don't quite understand your question right now

**Comment by Ocramius** [comment]
@lukaslangen I think my question is redundant: patch provides all answers :)

**Comment by weierophinney** [comment]
Completed in #60
