### ISSUE TITLE
500 error encountered when adding to routes.php.

### ISSUE THREAD

**Issue by junobartowski** [mezzio/mezzio-skeleton#65]
### Bug Report

I created an application with the following options:

composer create-project mezzio/mezzio-skeleton mezzio

- Modular (modular source code structure; recommended)
- laminas-servicemanager (supported by laminas)
- laminas-router (supported by laminas)
- laminas-view installs laminas-servicemanager (supported by laminas)
- Whoops (supported by laminas)

After creating the application, I ran `composer run --timeout=0 serve`. 
When the application is running, I ran `composer mezzio mezzio:module:create User` and the user is then created without errors. 
I registered it using `composer mezzio mezzio:module:register User` and created the handler using `composer mezzio mezzio:handler:create "User\Handler\RegisterHandler"`. No errors as well. 
So I continued adding the signup on the config/routes.php, `$app->route('/signup', \User\Handler\RegisterHandler::class, ['GET', 'POST'], 'signup');`. 
 
After visiting the application, this is what I got: 
 
#### Current behavior
 
<img width="430" alt="image" src="https://user-images.githubusercontent.com/9026660/153585711-9952e47e-9605-430b-9c69-76fccfcb7da4.png">
 
#### Expected behavior

I am expecting to see the text Template for User\Handler\RegisterHandler but it displays 500 error without an explanation. It is just something like this: 
 
<img width="538" alt="image" src="https://user-images.githubusercontent.com/9026660/153586989-d048cfbe-dfa6-4e30-8075-85a440c99b28.png">

**Comment by froschdesign** [comment]
@junobartowski 
> …it displays 500 error without an explanation.

Try to enable Whoops: https://docs.mezzio.dev/mezzio/v3/features/error-handling/#use-development-mode-configuration-to-enable-whoops

**Comment by junobartowski** [comment]
@froschdesign Thank you for the quick response. I was able to get the error now: 
  
Fatal error: Uncaught Laminas\ConfigAggregator\InvalidConfigProviderException: Cannot read config from Signup\ConfigProvider - class cannot be loaded. in /Documents/mezzio/mezzio/vendor/laminas/laminas-config-aggregator/src/InvalidConfigProviderException.php:19 Stack trace: #0 /Documents/mezzio/mezzio/vendor/laminas/laminas-config-aggregator/src/ConfigAggregator.php(106): Laminas\ConfigAggregator\InvalidConfigProviderException::fromNamedProvider('Signup\\ConfigPr...') #1 /Documents/mezzio/mezzio/vendor/laminas/laminas-config-aggregator/src/ConfigAggregator.php(220): Laminas\ConfigAggregator\ConfigAggregator->resolveProvider('Signup\\ConfigPr...') #2 /Documents/mezzio/mezzio/vendor/laminas/laminas-config-aggregator/src/ConfigAggregator.php(75): Laminas\ConfigAggregator\ConfigAggregator->loadConfigFromProviders(Array) #3 /Documents/mezzio/mezzio/config/config.php(51): Laminas\ConfigAggregator\ConfigAggregator->__construct(Array, 'data/cache/conf...') #4 /Documents/mezzio/mezzio/config/container.php(8): require('/...') #5 /Documents/mezzio/mezzio/public/index.php(18): require('/...') #6 /Documents/mezzio/mezzio/public/index.php(30): {closure}() #7 {main} thrown in /Documents/mezzio/mezzio/vendor/laminas/laminas-config-aggregator/src/InvalidConfigProviderException.php on line 19 
 
 I am new to Mezzio and still trying to learn.

**Comment by junobartowski** [comment]
This is the structure: 
 
<img width="333" alt="image" src="https://user-images.githubusercontent.com/9026660/153591279-3ada36ce-4b38-4a24-8d44-7b2cb30d0804.png">

**Comment by froschdesign** [comment]
The config provider of your `User` module is not the problem but there is config provider registered for `Signup`:

> `Cannot read config from Signup\ConfigProvider - class cannot be loaded.`

Please check the file `config/config.php` and search for `Signup\ConfigProvider::class` and remove it. Did you have a module called "Signup" before?

**Comment by junobartowski** [comment]
Yes it was a module I deleted a while ago. I removed it on the config and now this error shows on the file I haven't modified: 
 
`Too few arguments to function User\Handler\RegisterHandler::__construct(), 1 passed in /Documents/mezzio/mezzio/src/User/src/Handler/RegisterHandlerFactory.php on line 14 and exactly 2 expected`

**Comment by junobartowski** [comment]
Its the RegisterHandler I modified not the RegisterHandlerFactory which got affected. It is showing now. We can now close this.  Thank you very much for the quick help. 
 
<img width="379" alt="image" src="https://user-images.githubusercontent.com/9026660/153593614-472776b0-bed2-448f-b78b-fe24806000f3.png">

**Comment by froschdesign** [comment]
@junobartowski 
If you need further help, use our forums: https://discourse.laminas.dev
