### ISSUE TITLE
Unable to install on PHP8.1

### ISSUE THREAD

**Issue by SeriousKen** [mezzio/mezzio-skeleton#66]
Trying to create a new Mezzio project and falling at the first hurdle.

I'm running `composer create-project mezzio/mezzio-skeleton` then selecting all the defaults plus choosing plates for templating and I get the following.

```
Your lock file does not contain a compatible set of packages. Please run composer update.

  Problem 1
    - elie29/zend-phpdi-config is locked to version v6.0.0 and an update of this package was not requested.
    - elie29/zend-phpdi-config v6.0.0 requires php ^7.1 -> your php version (8.1.2) does not satisfy that requirement.
```

**Comment by arueckauer** [comment]
This is a pending issue. Have a look [here](https://github.com/mezzio/mezzio-skeleton/issues/46#issuecomment-844194868) for a solution.
