### ISSUE TITLE
getAffectedRows and count Always Returns 1

### ISSUE THREAD

**Issue by junobartowski** [mezzio/mezzio-skeleton#74]
This always return 1 even the data sent are the same values. Tried getAffectedRows() and count() but same result.

```
$where = new Where();
$where->equalTo($this->primaryKey, $data[$this->primaryKey]);
$update = $this->sql->update()->set($_data)->where($where) ;
return $this->sql->prepareStatementForSqlObject($update)->execute()->getAffectedRows() ;
```

Output:
<img width="75" alt="image" src="https://user-images.githubusercontent.com/9026660/185190032-7f9eae78-df09-4fe6-875b-f84ef74c65af.png">

**Comment by samsonasik** [comment]
I guess you're using laminas-db, if yes, you need to create issue at https://github.com/laminas/laminas-db/issues

**Comment by Ocramius** [comment]
Closing here, since it's unrelated to this repo.
